## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
   obj = bld.create_ns3_program('openflow-linear5-topology',
                                ['openflow', 'csma', 'internet', 'applications'])
   obj.source = 'openflow-linear5-topology.cc'